//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Gestión.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarCompañiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCompaniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCompaniasOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogeoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadosActivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarTerminalOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarTerminalActivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTerminalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarViajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarViajesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarViajesTodosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstadisticasOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeclaroVInternacionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeclaroVNacionalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Gestión.Properties.Settings.Default.Gestión_ServicioWeb_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarCompañiaCompletedEventHandler BuscarCompañiaCompleted;
        
        /// <remarks/>
        public event AltaCompaniaCompletedEventHandler AltaCompaniaCompleted;
        
        /// <remarks/>
        public event BajaCompaniaCompletedEventHandler BajaCompaniaCompleted;
        
        /// <remarks/>
        public event ModificarCompaniaCompletedEventHandler ModificarCompaniaCompleted;
        
        /// <remarks/>
        public event ListarCompaniasCompletedEventHandler ListarCompaniasCompleted;
        
        /// <remarks/>
        public event LogeoCompletedEventHandler LogeoCompleted;
        
        /// <remarks/>
        public event AltaEmpleadoCompletedEventHandler AltaEmpleadoCompleted;
        
        /// <remarks/>
        public event BajaEmpleadoCompletedEventHandler BajaEmpleadoCompleted;
        
        /// <remarks/>
        public event ModificarEmpleadoCompletedEventHandler ModificarEmpleadoCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadosActivosCompletedEventHandler BuscarEmpleadosActivosCompleted;
        
        /// <remarks/>
        public event AltaTerminalCompletedEventHandler AltaTerminalCompleted;
        
        /// <remarks/>
        public event BajaTerminalCompletedEventHandler BajaTerminalCompleted;
        
        /// <remarks/>
        public event ModificarTerminalCompletedEventHandler ModificarTerminalCompleted;
        
        /// <remarks/>
        public event BuscarTerminalActivaCompletedEventHandler BuscarTerminalActivaCompleted;
        
        /// <remarks/>
        public event ListarTerminalesCompletedEventHandler ListarTerminalesCompleted;
        
        /// <remarks/>
        public event AltaViajeCompletedEventHandler AltaViajeCompleted;
        
        /// <remarks/>
        public event BajaViajeCompletedEventHandler BajaViajeCompleted;
        
        /// <remarks/>
        public event ModificarViajeCompletedEventHandler ModificarViajeCompleted;
        
        /// <remarks/>
        public event BuscarViajeCompletedEventHandler BuscarViajeCompleted;
        
        /// <remarks/>
        public event ListarViajesCompletedEventHandler ListarViajesCompleted;
        
        /// <remarks/>
        public event ListarViajesTodosCompletedEventHandler ListarViajesTodosCompleted;
        
        /// <remarks/>
        public event EstadisticasCompletedEventHandler EstadisticasCompleted;
        
        /// <remarks/>
        public event DeclaroVInternacionalCompletedEventHandler DeclaroVInternacionalCompleted;
        
        /// <remarks/>
        public event DeclaroVNacionalCompletedEventHandler DeclaroVNacionalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCompañia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania BuscarCompañia(string nombre) {
            object[] results = this.Invoke("BuscarCompañia", new object[] {
                        nombre});
            return ((Compania)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCompañiaAsync(string nombre) {
            this.BuscarCompañiaAsync(nombre, null);
        }
        
        /// <remarks/>
        public void BuscarCompañiaAsync(string nombre, object userState) {
            if ((this.BuscarCompañiaOperationCompleted == null)) {
                this.BuscarCompañiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCompañiaOperationCompleted);
            }
            this.InvokeAsync("BuscarCompañia", new object[] {
                        nombre}, this.BuscarCompañiaOperationCompleted, userState);
        }
        
        private void OnBuscarCompañiaOperationCompleted(object arg) {
            if ((this.BuscarCompañiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCompañiaCompleted(this, new BuscarCompañiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCompania(Compania C) {
            this.Invoke("AltaCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void AltaCompaniaAsync(Compania C) {
            this.AltaCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void AltaCompaniaAsync(Compania C, object userState) {
            if ((this.AltaCompaniaOperationCompleted == null)) {
                this.AltaCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaCompaniaOperationCompleted);
            }
            this.InvokeAsync("AltaCompania", new object[] {
                        C}, this.AltaCompaniaOperationCompleted, userState);
        }
        
        private void OnAltaCompaniaOperationCompleted(object arg) {
            if ((this.AltaCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCompania(Compania C) {
            this.Invoke("BajaCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void BajaCompaniaAsync(Compania C) {
            this.BajaCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void BajaCompaniaAsync(Compania C, object userState) {
            if ((this.BajaCompaniaOperationCompleted == null)) {
                this.BajaCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaCompaniaOperationCompleted);
            }
            this.InvokeAsync("BajaCompania", new object[] {
                        C}, this.BajaCompaniaOperationCompleted, userState);
        }
        
        private void OnBajaCompaniaOperationCompleted(object arg) {
            if ((this.BajaCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCompania", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCompania(Compania C) {
            this.Invoke("ModificarCompania", new object[] {
                        C});
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania C) {
            this.ModificarCompaniaAsync(C, null);
        }
        
        /// <remarks/>
        public void ModificarCompaniaAsync(Compania C, object userState) {
            if ((this.ModificarCompaniaOperationCompleted == null)) {
                this.ModificarCompaniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCompaniaOperationCompleted);
            }
            this.InvokeAsync("ModificarCompania", new object[] {
                        C}, this.ModificarCompaniaOperationCompleted, userState);
        }
        
        private void OnModificarCompaniaOperationCompleted(object arg) {
            if ((this.ModificarCompaniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCompaniaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCompanias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Compania[] ListarCompanias() {
            object[] results = this.Invoke("ListarCompanias", new object[0]);
            return ((Compania[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync() {
            this.ListarCompaniasAsync(null);
        }
        
        /// <remarks/>
        public void ListarCompaniasAsync(object userState) {
            if ((this.ListarCompaniasOperationCompleted == null)) {
                this.ListarCompaniasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCompaniasOperationCompleted);
            }
            this.InvokeAsync("ListarCompanias", new object[0], this.ListarCompaniasOperationCompleted, userState);
        }
        
        private void OnListarCompaniasOperationCompleted(object arg) {
            if ((this.ListarCompaniasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompaniasCompleted(this, new ListarCompaniasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logeo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado Logeo(int ci, string contraseña) {
            object[] results = this.Invoke("Logeo", new object[] {
                        ci,
                        contraseña});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void LogeoAsync(int ci, string contraseña) {
            this.LogeoAsync(ci, contraseña, null);
        }
        
        /// <remarks/>
        public void LogeoAsync(int ci, string contraseña, object userState) {
            if ((this.LogeoOperationCompleted == null)) {
                this.LogeoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogeoOperationCompleted);
            }
            this.InvokeAsync("Logeo", new object[] {
                        ci,
                        contraseña}, this.LogeoOperationCompleted, userState);
        }
        
        private void OnLogeoOperationCompleted(object arg) {
            if ((this.LogeoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogeoCompleted(this, new LogeoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaEmpleado(Empleado E) {
            this.Invoke("AltaEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void AltaEmpleadoAsync(Empleado E) {
            this.AltaEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void AltaEmpleadoAsync(Empleado E, object userState) {
            if ((this.AltaEmpleadoOperationCompleted == null)) {
                this.AltaEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaEmpleadoOperationCompleted);
            }
            this.InvokeAsync("AltaEmpleado", new object[] {
                        E}, this.AltaEmpleadoOperationCompleted, userState);
        }
        
        private void OnAltaEmpleadoOperationCompleted(object arg) {
            if ((this.AltaEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaEmpleado(Empleado E) {
            this.Invoke("BajaEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void BajaEmpleadoAsync(Empleado E) {
            this.BajaEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void BajaEmpleadoAsync(Empleado E, object userState) {
            if ((this.BajaEmpleadoOperationCompleted == null)) {
                this.BajaEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaEmpleadoOperationCompleted);
            }
            this.InvokeAsync("BajaEmpleado", new object[] {
                        E}, this.BajaEmpleadoOperationCompleted, userState);
        }
        
        private void OnBajaEmpleadoOperationCompleted(object arg) {
            if ((this.BajaEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmpleado(Empleado E) {
            this.Invoke("ModificarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E) {
            this.ModificarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E, object userState) {
            if ((this.ModificarEmpleadoOperationCompleted == null)) {
                this.ModificarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("ModificarEmpleado", new object[] {
                        E}, this.ModificarEmpleadoOperationCompleted, userState);
        }
        
        private void OnModificarEmpleadoOperationCompleted(object arg) {
            if ((this.ModificarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpleadosActivos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado BuscarEmpleadosActivos(int ci) {
            object[] results = this.Invoke("BuscarEmpleadosActivos", new object[] {
                        ci});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadosActivosAsync(int ci) {
            this.BuscarEmpleadosActivosAsync(ci, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadosActivosAsync(int ci, object userState) {
            if ((this.BuscarEmpleadosActivosOperationCompleted == null)) {
                this.BuscarEmpleadosActivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadosActivosOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleadosActivos", new object[] {
                        ci}, this.BuscarEmpleadosActivosOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadosActivosOperationCompleted(object arg) {
            if ((this.BuscarEmpleadosActivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadosActivosCompleted(this, new BuscarEmpleadosActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaTerminal(Terminal T) {
            this.Invoke("AltaTerminal", new object[] {
                        T});
        }
        
        /// <remarks/>
        public void AltaTerminalAsync(Terminal T) {
            this.AltaTerminalAsync(T, null);
        }
        
        /// <remarks/>
        public void AltaTerminalAsync(Terminal T, object userState) {
            if ((this.AltaTerminalOperationCompleted == null)) {
                this.AltaTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaTerminalOperationCompleted);
            }
            this.InvokeAsync("AltaTerminal", new object[] {
                        T}, this.AltaTerminalOperationCompleted, userState);
        }
        
        private void OnAltaTerminalOperationCompleted(object arg) {
            if ((this.AltaTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaTerminal(Terminal T) {
            this.Invoke("BajaTerminal", new object[] {
                        T});
        }
        
        /// <remarks/>
        public void BajaTerminalAsync(Terminal T) {
            this.BajaTerminalAsync(T, null);
        }
        
        /// <remarks/>
        public void BajaTerminalAsync(Terminal T, object userState) {
            if ((this.BajaTerminalOperationCompleted == null)) {
                this.BajaTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaTerminalOperationCompleted);
            }
            this.InvokeAsync("BajaTerminal", new object[] {
                        T}, this.BajaTerminalOperationCompleted, userState);
        }
        
        private void OnBajaTerminalOperationCompleted(object arg) {
            if ((this.BajaTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarTerminal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarTerminal(Terminal T) {
            this.Invoke("ModificarTerminal", new object[] {
                        T});
        }
        
        /// <remarks/>
        public void ModificarTerminalAsync(Terminal T) {
            this.ModificarTerminalAsync(T, null);
        }
        
        /// <remarks/>
        public void ModificarTerminalAsync(Terminal T, object userState) {
            if ((this.ModificarTerminalOperationCompleted == null)) {
                this.ModificarTerminalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarTerminalOperationCompleted);
            }
            this.InvokeAsync("ModificarTerminal", new object[] {
                        T}, this.ModificarTerminalOperationCompleted, userState);
        }
        
        private void OnModificarTerminalOperationCompleted(object arg) {
            if ((this.ModificarTerminalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarTerminalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarTerminalActiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminal BuscarTerminalActiva(string codigo) {
            object[] results = this.Invoke("BuscarTerminalActiva", new object[] {
                        codigo});
            return ((Terminal)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarTerminalActivaAsync(string codigo) {
            this.BuscarTerminalActivaAsync(codigo, null);
        }
        
        /// <remarks/>
        public void BuscarTerminalActivaAsync(string codigo, object userState) {
            if ((this.BuscarTerminalActivaOperationCompleted == null)) {
                this.BuscarTerminalActivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarTerminalActivaOperationCompleted);
            }
            this.InvokeAsync("BuscarTerminalActiva", new object[] {
                        codigo}, this.BuscarTerminalActivaOperationCompleted, userState);
        }
        
        private void OnBuscarTerminalActivaOperationCompleted(object arg) {
            if ((this.BuscarTerminalActivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarTerminalActivaCompleted(this, new BuscarTerminalActivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTerminales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Terminal[] ListarTerminales() {
            object[] results = this.Invoke("ListarTerminales", new object[0]);
            return ((Terminal[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTerminalesAsync() {
            this.ListarTerminalesAsync(null);
        }
        
        /// <remarks/>
        public void ListarTerminalesAsync(object userState) {
            if ((this.ListarTerminalesOperationCompleted == null)) {
                this.ListarTerminalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTerminalesOperationCompleted);
            }
            this.InvokeAsync("ListarTerminales", new object[0], this.ListarTerminalesOperationCompleted, userState);
        }
        
        private void OnListarTerminalesOperationCompleted(object arg) {
            if ((this.ListarTerminalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTerminalesCompleted(this, new ListarTerminalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaViaje(Viajes V) {
            this.Invoke("AltaViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void AltaViajeAsync(Viajes V) {
            this.AltaViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void AltaViajeAsync(Viajes V, object userState) {
            if ((this.AltaViajeOperationCompleted == null)) {
                this.AltaViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaViajeOperationCompleted);
            }
            this.InvokeAsync("AltaViaje", new object[] {
                        V}, this.AltaViajeOperationCompleted, userState);
        }
        
        private void OnAltaViajeOperationCompleted(object arg) {
            if ((this.AltaViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaViaje(Viajes V) {
            this.Invoke("BajaViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void BajaViajeAsync(Viajes V) {
            this.BajaViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void BajaViajeAsync(Viajes V, object userState) {
            if ((this.BajaViajeOperationCompleted == null)) {
                this.BajaViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaViajeOperationCompleted);
            }
            this.InvokeAsync("BajaViaje", new object[] {
                        V}, this.BajaViajeOperationCompleted, userState);
        }
        
        private void OnBajaViajeOperationCompleted(object arg) {
            if ((this.BajaViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarViaje(Viajes V) {
            this.Invoke("ModificarViaje", new object[] {
                        V});
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viajes V) {
            this.ModificarViajeAsync(V, null);
        }
        
        /// <remarks/>
        public void ModificarViajeAsync(Viajes V, object userState) {
            if ((this.ModificarViajeOperationCompleted == null)) {
                this.ModificarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarViajeOperationCompleted);
            }
            this.InvokeAsync("ModificarViaje", new object[] {
                        V}, this.ModificarViajeOperationCompleted, userState);
        }
        
        private void OnModificarViajeOperationCompleted(object arg) {
            if ((this.ModificarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarViajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarViaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viajes BuscarViaje(int numero) {
            object[] results = this.Invoke("BuscarViaje", new object[] {
                        numero});
            return ((Viajes)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int numero) {
            this.BuscarViajeAsync(numero, null);
        }
        
        /// <remarks/>
        public void BuscarViajeAsync(int numero, object userState) {
            if ((this.BuscarViajeOperationCompleted == null)) {
                this.BuscarViajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarViajeOperationCompleted);
            }
            this.InvokeAsync("BuscarViaje", new object[] {
                        numero}, this.BuscarViajeOperationCompleted, userState);
        }
        
        private void OnBuscarViajeOperationCompleted(object arg) {
            if ((this.BuscarViajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarViajeCompleted(this, new BuscarViajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarViajes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viajes[] ListarViajes() {
            object[] results = this.Invoke("ListarViajes", new object[0]);
            return ((Viajes[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarViajesAsync() {
            this.ListarViajesAsync(null);
        }
        
        /// <remarks/>
        public void ListarViajesAsync(object userState) {
            if ((this.ListarViajesOperationCompleted == null)) {
                this.ListarViajesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarViajesOperationCompleted);
            }
            this.InvokeAsync("ListarViajes", new object[0], this.ListarViajesOperationCompleted, userState);
        }
        
        private void OnListarViajesOperationCompleted(object arg) {
            if ((this.ListarViajesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarViajesCompleted(this, new ListarViajesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarViajesTodos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Viajes[] ListarViajesTodos() {
            object[] results = this.Invoke("ListarViajesTodos", new object[0]);
            return ((Viajes[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarViajesTodosAsync() {
            this.ListarViajesTodosAsync(null);
        }
        
        /// <remarks/>
        public void ListarViajesTodosAsync(object userState) {
            if ((this.ListarViajesTodosOperationCompleted == null)) {
                this.ListarViajesTodosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarViajesTodosOperationCompleted);
            }
            this.InvokeAsync("ListarViajesTodos", new object[0], this.ListarViajesTodosOperationCompleted, userState);
        }
        
        private void OnListarViajesTodosOperationCompleted(object arg) {
            if ((this.ListarViajesTodosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarViajesTodosCompleted(this, new ListarViajesTodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Estadisticas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Estadisticas() {
            object[] results = this.Invoke("Estadisticas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EstadisticasAsync() {
            this.EstadisticasAsync(null);
        }
        
        /// <remarks/>
        public void EstadisticasAsync(object userState) {
            if ((this.EstadisticasOperationCompleted == null)) {
                this.EstadisticasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstadisticasOperationCompleted);
            }
            this.InvokeAsync("Estadisticas", new object[0], this.EstadisticasOperationCompleted, userState);
        }
        
        private void OnEstadisticasOperationCompleted(object arg) {
            if ((this.EstadisticasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstadisticasCompleted(this, new EstadisticasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeclaroVInternacional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Internacionales DeclaroVInternacional(Internacionales I) {
            object[] results = this.Invoke("DeclaroVInternacional", new object[] {
                        I});
            return ((Internacionales)(results[0]));
        }
        
        /// <remarks/>
        public void DeclaroVInternacionalAsync(Internacionales I) {
            this.DeclaroVInternacionalAsync(I, null);
        }
        
        /// <remarks/>
        public void DeclaroVInternacionalAsync(Internacionales I, object userState) {
            if ((this.DeclaroVInternacionalOperationCompleted == null)) {
                this.DeclaroVInternacionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeclaroVInternacionalOperationCompleted);
            }
            this.InvokeAsync("DeclaroVInternacional", new object[] {
                        I}, this.DeclaroVInternacionalOperationCompleted, userState);
        }
        
        private void OnDeclaroVInternacionalOperationCompleted(object arg) {
            if ((this.DeclaroVInternacionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeclaroVInternacionalCompleted(this, new DeclaroVInternacionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeclaroVNacional", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Nacionales DeclaroVNacional(Nacionales N) {
            object[] results = this.Invoke("DeclaroVNacional", new object[] {
                        N});
            return ((Nacionales)(results[0]));
        }
        
        /// <remarks/>
        public void DeclaroVNacionalAsync(Nacionales N) {
            this.DeclaroVNacionalAsync(N, null);
        }
        
        /// <remarks/>
        public void DeclaroVNacionalAsync(Nacionales N, object userState) {
            if ((this.DeclaroVNacionalOperationCompleted == null)) {
                this.DeclaroVNacionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeclaroVNacionalOperationCompleted);
            }
            this.InvokeAsync("DeclaroVNacional", new object[] {
                        N}, this.DeclaroVNacionalOperationCompleted, userState);
        }
        
        private void OnDeclaroVNacionalOperationCompleted(object arg) {
            if ((this.DeclaroVNacionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeclaroVNacionalCompleted(this, new DeclaroVNacionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Compania {
        
        private string nombreField;
        
        private string direccionField;
        
        private long telefonoField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public long telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nacionales))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Internacionales))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Viajes {
        
        private int numeroField;
        
        private int cantAsientosField;
        
        private System.DateTime partidaField;
        
        private System.DateTime arriboField;
        
        private Empleado eField;
        
        private Terminal tField;
        
        private Compania cField;
        
        /// <remarks/>
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public int cantAsientos {
            get {
                return this.cantAsientosField;
            }
            set {
                this.cantAsientosField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime arribo {
            get {
                return this.arriboField;
            }
            set {
                this.arriboField = value;
            }
        }
        
        /// <remarks/>
        public Empleado e {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        public Terminal t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        public Compania c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private int ciField;
        
        private string nombreCompletoField;
        
        private string contraseñaField;
        
        /// <remarks/>
        public int ci {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <remarks/>
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <remarks/>
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Terminal {
        
        private string codigoField;
        
        private string ciudadField;
        
        private string paisField;
        
        private string[] facilidadesField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string[] facilidades {
            get {
                return this.facilidadesField;
            }
            set {
                this.facilidadesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nacionales : Viajes {
        
        private int paradasField;
        
        /// <remarks/>
        public int paradas {
            get {
                return this.paradasField;
            }
            set {
                this.paradasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Internacionales : Viajes {
        
        private bool servAbordoField;
        
        private string documentacionField;
        
        /// <remarks/>
        public bool servAbordo {
            get {
                return this.servAbordoField;
            }
            set {
                this.servAbordoField = value;
            }
        }
        
        /// <remarks/>
        public string documentacion {
            get {
                return this.documentacionField;
            }
            set {
                this.documentacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarCompañiaCompletedEventHandler(object sender, BuscarCompañiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCompañiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCompañiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AltaCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BajaCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ModificarCompaniaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarCompaniasCompletedEventHandler(object sender, ListarCompaniasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompaniasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompaniasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Compania[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Compania[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LogeoCompletedEventHandler(object sender, LogeoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogeoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogeoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AltaEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BajaEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ModificarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarEmpleadosActivosCompletedEventHandler(object sender, BuscarEmpleadosActivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadosActivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadosActivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AltaTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BajaTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ModificarTerminalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarTerminalActivaCompletedEventHandler(object sender, BuscarTerminalActivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarTerminalActivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarTerminalActivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarTerminalesCompletedEventHandler(object sender, ListarTerminalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTerminalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTerminalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Terminal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Terminal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AltaViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BajaViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ModificarViajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarViajeCompletedEventHandler(object sender, BuscarViajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarViajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarViajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viajes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viajes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarViajesCompletedEventHandler(object sender, ListarViajesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarViajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarViajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viajes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viajes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ListarViajesTodosCompletedEventHandler(object sender, ListarViajesTodosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarViajesTodosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarViajesTodosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Viajes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Viajes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void EstadisticasCompletedEventHandler(object sender, EstadisticasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstadisticasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstadisticasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeclaroVInternacionalCompletedEventHandler(object sender, DeclaroVInternacionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeclaroVInternacionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeclaroVInternacionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Internacionales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Internacionales)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeclaroVNacionalCompletedEventHandler(object sender, DeclaroVNacionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeclaroVNacionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeclaroVNacionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Nacionales Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nacionales)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591